# Creating SNS Topic
BoilerplateSNSTopic: 
  Type: AWS::SNS::Topic
  Properties:
    DisplayName: "AWS Alert"
    Subscription: 
      - 
        Endpoint: "lambda@hotmail.com"
        Protocol: "email"
    TopicName: lambda-boilerplate-${self:custom.stage}-lambda-alert

# Create CloudWatch Alarm for Error
BoilerplateLambdaErrorAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    ActionsEnabled: True
    AlarmActions:
      - Ref: BoilerplateSNSTopic
    AlarmDescription: "Lambda Function Error"
    AlarmName: lambda-boilerplate-${self:custom.stage}-lambda-error
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: FunctionName
        Value: ${self:custom.functionName}
    EvaluationPeriods: 1
    Namespace: AWS/Lambda
    MetricName: Errors
    Statistic: Average
    TreatMissingData: notBreaching
    Period: 60
    Threshold: 1.0

# Create CloudWatch Alarm for Error
BoilerplateLambdaRunningTooLongAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    ActionsEnabled: True
    AlarmActions:
      - Ref: BoilerplateSNSTopic
    AlarmDescription: "Lambda Function Running Too Long"
    AlarmName: lambda-boilerplate-${self:custom.stage}-lambda-error-Running-too-Long
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: FunctionName
        Value: ${self:custom.functionName}
    EvaluationPeriods: 1
    Namespace: AWS/Lambda
    MetricName: Duration
    Statistic: Average
    TreatMissingData: notBreaching
    Period: 300
    Threshold: 28500

# 4XX Error for API Gateway
BoilerplateApi4xxErrors:
  Type: AWS::CloudWatch::Alarm
  Properties:
    ActionsEnabled: True
    AlarmActions:
      - Ref: BoilerPlateSNSTopic
    AlarmDescription: "API Gateway is giving 4XX Error"
    AlarmName: lambda-boilerplate-${self:custom.stage}-api-4xx-errors
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: ApiName
        Value: ${self:custom.functionName}
    EvaluationPeriods: 1
    Namespace: AWS/ApiGateway
    MetricName: 4XXError
    Statistic: Average
    TreatMissingData: notBreaching
    Period: 60
    Threshold: 1.0

# 5XX Error for API Gateway
BoilerplateApi5xxErrors:
  Type: AWS::CloudWatch::Alarm
  Properties:
    ActionsEnabled: True
    AlarmActions:
      - Ref: BoilerplateSNSTopic
    AlarmDescription: "API Gateway is giving 5XX Error"
    AlarmName: Boilerplate-${self:custom.stage}-student-degree-match-api-5xx-errors
    ComparisonOperator: GreaterThanOrEqualToThreshold
    Dimensions:
      - Name: ApiName
        Value: ${self:custom.functionName}
    EvaluationPeriods: 1
    Namespace: AWS/ApiGateway
    MetricName: 5XXError
    Statistic: Average
    TreatMissingData: notBreaching
    Period: 60
    Threshold: 1.0